import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Not application source: generated/reference design tooling output and
    // the standalone Linear skill (its own package, linted separately).
    "design/**",
    "linear-skill/**",
    ".claude/**",
    // Auto-generated by `npx convex dev`/`convex deploy` - regenerated on
    // every push, not hand-authored, re-linting it is noise not signal.
    "convex/_generated/**",
  ]),
]);

export default eslintConfig;
